### ISSUE TITLE
Error: `leaf-tree--setup: Wrong number of arguments`

### ISSUE THREAD

**Issue by fernandodemorais-jf** [conao3/leaf-tree.el#4]
Hello,

When I load `leaf-tree-mode` the following error message appears in echo area:

```emacs-lisp
leaf-tree--setup: Wrong number of arguments: #[(&optional force-update) "Æ2m\0Ç ?\0\0È!\0	U?k\0	É1+\0Ê 0;\08\0ËÆÌ\":\0Í )M\0Î!M\0
V\0rÏ qÐ )^\0Ñ f\0Ò ÓÔ!Ì*0" [imenu-list--imenu-entries location old-entries force-update imenu-list--last-location err index-failure point-marker marker-buffer (imenu-unavailable) ...] 3 ("/home/fernando/.config/emacs/elpa/imenu-list-20210411.1703/imenu-list.elc" . 17611)], 2
```

If I try to display or go to the desired entry, the cursor is moved to a completely different one.

This is my `leaf-tree` configuration:

```emacs-lisp
(leaf leaf-tree
  :ensure t
  :bind ("C-c l t" . leaf-tree-mode)
  :custom ((imenu-list-focus-after-activation . t)
	   (imenu-list-size . 30)
	   (imenu-list-position . 'left)))
```

Thanks!

**Comment by conao3** [comment]
Thanks, good catch.
I think #5 should fix this issue. Thanks for using my package!

**Comment by fernandodemorais-jf** [comment]
Hello @conao3!

I'm still experiencing the following issue, when using the `leaf-tree`:

> If I try to display or go to the desired entry, the cursor is moved to a completely different one.

`imenu-list` work as intended.

Thanks!

**Comment by conao3** [comment]
OK, thanks for reporting this issue! I'll investigate it later.

**Comment by JeremPFT** [comment]
I think this is the problem I solved in #8

**Comment by fernandodemorais-jf** [comment]
> I think this is the problem I solved in #8

Yeah, it solved! Thanks!
